name: RadiRoot
version: 2.7
date: 2014-04-09
description: |
    Roots of a Polynomial as Radicals

authors:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de

maintainers:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de

GAP: ">=4.4"

needed-pkgs:
    - name: "Alnuth"
      version: ">=2.2.3"
      url: "https://gap-packages.github.io/alnuth"

www: http://www.icm.tu-bs.de/ag_algebra/software/radiroot/
readme: README
packageinfo: http://www.icm.tu-bs.de/ag_algebra/software/radiroot/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/ag_algebra/software/radiroot/radiroot-2.7.tar.gz

abstract: |
    The <span class="pkgname">RadiRoot</span> package installs a method to    display the roots of a rational polynomial as radicals if it is solvable.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
